# Generated by Django 2.2.5 on 2019-09-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_auto_20190907_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldetails',
            name='urlname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
